# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Splitly V2"
product_name = "Splitly V2"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "manni"
chip = "nrf52840"

[layout]
rows = 5
cols = 12
layers = 4
keymap = [
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Backspace"],
        ["Tab", "Q", "W", "F", "P", "B", "J", "L", "U", "Y", "Semicolon", "Backslash"],
        ["CapsLock", "A", "R", "S", "T", "G", "M", "N", "E", "I", "O", "Enter"],
        ["LShift", "Z", "X", "C", "D", "V", "K", "H", "Comma", "Dot", "Slash", "UP"],
        ["LCtrl", "LGui", "LAlt", "_", "_", "Space", "_", "_", "MO(1)", "Left", "Down", "Right"]
    ],
    [
        ["Grave", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "Delete"],
        ["_", "User0", "User1", "User2", "User3", "User4", "User5", "User6", "User7", "_", "_", "_"],
        ["_", "User8", "User9", "User10", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ]
]

[split]
connection = "ble"

# Left half - Central
[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0

[split.central.matrix]
matrix_type = "normal"
input_pins = ["P1_11", "P1_10", "P0_03", "P0_28", "P1_13"]
output_pins = ["P0_30", "P0_31", "P0_29", "P0_02", "P0_05", "P1_09"]

# Right half - Peripheral
[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 6

[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["P1_11", "P1_10", "P0_03", "P0_28", "P1_13"]
output_pins = ["P0_30", "P0_31", "P0_29", "P0_02", "P0_05", "P1_09"]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
capslock = { pin = "P0_26", low_active = false }
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
enabled = true
num_sectors = 32

[ble]
enabled = true
battery_adc_pin = "P0_04" # AIN_2
charge_state.pin = "P0_07"
charge_state.low_active = true
charge_led.pin = "P0_08"
charge_led.low_active = false
adc_divider_measured = 2000
adc_divider_total = 2806

[rmk]
ble_profiles = 3
